# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: cypress/base:latest

pipelines:
  default:
    - step:
        name: 'Install packages & Run Cypress'
        script:
          - npm ci
          - npm run test
