#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
 #  - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
#              - npm install
#              - npm test
              # install dependencies
              - npm ci
              # start the server in the background
              - npm run start:ci &
              # run Cypress tests
              - npm run e2e